### ISSUE TITLE
Feature Request: Create a small gui to configure the save file location

### ISSUE THREAD

**Issue by AlexCory** [fuzzyCute/Idle_home_Auto_save#1]
Please add a gui with the following features:

* Small Simple Window
* A text field to a file path for a .txt file where the auto save file will be saved.
* A browse button that allows users to pick where the auto save .txt file will be saved and what file name it will be.
* A save button that will save the settings in a .config file
* When the window loads for the first time, have it read the config file and load all the settings.
* A small text window at the bottom to show the console output / log.

**Comment by fuzzyCute** [comment]
Done!
Except for the .config file, don't thing it's needed for this simple project
Thanks for the suggestions
