### ISSUE TITLE
Slight issue when multiple saves are found

### ISSUE THREAD

**Issue by M1XZG** [fuzzyCute/Idle_home_Auto_save#3]
You can see the first 2 saves shown here are in order, but then I saved the game twice in a couple of minutes, it found 2 updates but they're inserted into the file in the wrong time order.

![Snag_15c9fbaf](https://user-images.githubusercontent.com/22931360/236930710-e43f994d-127d-4b77-b31c-509f50957424.png)

Kind of odd.

**Comment by M1XZG** [comment]
Seems like maybe when the program has been restarted and the destination file has been opened again? Not sure, needs some more debugging maybe.

**Comment by fuzzyCute** [comment]
Yeah i wasn't sorting the saves, but now with the new version it should fix it
